from __future__ import annotations

from app.analyzers.base import AnalyzerResult

CATEGORY_COPY = {
    "style_homogeneity": {
        "title": "Break up uniform style — add human variance",
        "why": "Identical naming, function shapes, and imports are an AI-generated tell and make refactors risky.",
        "effort": "S",
    },
    "duplication": {
        "title": "Deduplicate copy-pasted logic",
        "why": "Repeated blocks across files create divergent fixes and hidden bugs.",
        "effort": "M",
    },
    "comment_patterns": {
        "title": "Remove or rewrite generic AI comments",
        "why": "High-volume generic comments hide intent and signal autogenerated code.",
        "effort": "S",
    },
    "error_handling": {
        "title": "Tighten error handling",
        "why": "Silent except blocks swallow production failures and make incidents hard to debug.",
        "effort": "M",
    },
    "architectural_contracts": {
        "title": "Add type contracts and split large units",
        "why": "Missing types and 500+ line functions block safe refactors and onboarding.",
        "effort": "L",
    },
    "dependency_graph": {
        "title": "Resolve import cycles and high fan-out",
        "why": "Circular imports and scattered env access cause fragile module loading.",
        "effort": "M",
    },
    "code_churn": {
        "title": "Stabilize high-churn files",
        "why": "Files getting re-edited within 2 weeks of creation are probably vibe-fixed — add tests.",
        "effort": "M",
    },
}


def build_action_plan(results: dict[str, AnalyzerResult], limit: int = 6) -> list[dict]:
    ordered = sorted(
        ((name, r) for name, r in results.items() if not r.skipped),
        key=lambda item: item[1].repo_score,
        reverse=True,
    )
    plan: list[dict] = []
    for priority, (name, res) in enumerate(ordered, start=1):
        if res.repo_score < 25:
            continue
        top_files = sorted(res.file_results, key=lambda fr: fr.score, reverse=True)[:5]
        copy = CATEGORY_COPY.get(name, {"title": name, "why": "", "effort": "M"})
        plan.append(
            {
                "priority": priority,
                "category": name,
                "title": copy["title"],
                "why": copy["why"],
                "effort": copy["effort"],
                "score": round(res.repo_score, 1),
                "files": [{"path": fr.path, "score": round(fr.score, 1)} for fr in top_files],
            }
        )
        if len(plan) >= limit:
            break
    return plan
